In [2]:
import numpy as np

### 파일 처리

In [7]:
# 파일 저장(tofile)
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[ 1.06280276 -0.45325563 -1.75642458  0.87793083  1.27385786]
 [-1.21064817  1.98653335  0.06695576 -0.10245002 -0.59917824]
 [ 0.59926986  0.8224285  -0.72056861 -0.03360266 -0.9725805 ]]


In [10]:
# 파일 불러오기(fromfile)
m = np.fromfile('C:\STUDY\StudyPython_kim\day2/n.npy')
print(m)

[ 1.06280276 -0.45325563 -1.75642458  0.87793083  1.27385786 -1.21064817
  1.98653335  0.06695576 -0.10245002 -0.59917824  0.59926986  0.8224285
 -0.72056861 -0.03360266 -0.9725805 ]


In [13]:
# 파일 저장, 불러오기(np.save, np.load)
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[ 1.06280276 -0.45325563 -1.75642458  0.87793083  1.27385786]
 [-1.21064817  1.98653335  0.06695576 -0.10245002 -0.59917824]
 [ 0.59926986  0.8224285  -0.72056861 -0.03360266 -0.9725805 ]]


In [ ]:
# txt 파일 저장(np.)